# Creating this compose file to build all images and run all containers
# in on go.
version: '3.8'
services:
  discovery-service:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
  gateway-service:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      DISCOVERY_SERVER: eureka-server
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
  product-service:
    build: ./restaurant-service
    container_name: restaurant-service
    environment:
      DISCOVERY_SERVER: eureka-server
    depends_on:
      - eureka-server
      - api-gateway
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DISCOVERY_SERVER: eureka-server
    depends_on:
      - eureka-server
      - api-gateway